name: codequality
on: [pull_request]
jobs:
  security:
    name: gosec, Inspects source code for security problems
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-exclude-dir=testutils ./...'
  format:
    name: fmt, makes sure there are no formatting issues
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Run fmt
        run: make format
  mod_tidy:
    name: go mod tidy, makes sure are dependencies are cool
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Run go mod tidy
        run: make tidy
