name: Test

on:
  pull_request:
    branches: [ main ]

env:
  go_version: 1.16

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.go_version }}

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out ./...

    - name: Convert  go coverage report to lcov format
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
        infile: coverage.out
        outfile: coverage.lcov

    - name: Report coverage
      uses: vebr/jest-lcov-reporter@v0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage.lcov
